# Generated by Django 4.1.2 on 2022-10-31 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerProflie',
            new_name='TrainerProfile',
        ),
    ]
