# Generated by Django 4.1.2 on 2022-10-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_trainerproflie_trainerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='certs',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='email',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='facebook',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='first_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='instagram',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='last_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='personal_site',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='specialties',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='twitter',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
