# Generated by Django 4.1.2 on 2022-11-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainerprofile_clientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='joined_on',
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='location',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='personal_site',
            field=models.URLField(max_length=225, null=True),
        ),
    ]
