# Generated by Django 4.1.2 on 2022-11-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_trainerprofile_joined_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='personal_site',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
