# Generated by Django 4.1.2 on 2022-11-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_trainerprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='business',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
