# Generated by Django 4.1.2 on 2022-11-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clientprofile_user_alter_trainerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='training_type',
            field=models.CharField(choices=[('In Person', 'In Person'), ('Online', 'Online'), ('In Person & Online', 'In Person & Online')], default='In Person', max_length=20),
        ),
    ]
