# Generated by Django 4.1.2 on 2022-11-12 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_review_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image1', models.ImageField(null=True, upload_to='posts/')),
                ('post_title1', models.CharField(max_length=225, null=True)),
                ('post_caption1', models.CharField(max_length=225, null=True)),
                ('post_image2', models.ImageField(null=True, upload_to='posts/')),
                ('post_title2', models.CharField(max_length=225, null=True)),
                ('post_caption2', models.CharField(max_length=225, null=True)),
                ('post_image3', models.ImageField(null=True, upload_to='posts/')),
                ('post_title3', models.CharField(max_length=225, null=True)),
                ('post_caption3', models.CharField(max_length=225, null=True)),
                ('trainerprofile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainerprofile')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
