# Generated by Django 4.1.2 on 2022-11-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_headlinepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinepost',
            name='post_caption1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_caption2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_caption3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_image1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_image2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_image3',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_title1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_title2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_title3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
