# Generated by Django 4.1.2 on 2022-11-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_headlinepost_post_caption1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinepost',
            name='trainerprofile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainerprofile'),
        ),
    ]
