# Generated by Django 4.1.2 on 2022-11-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_headlinepost_trainerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
