# Generated by Django 4.1.2 on 2022-11-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_trainerprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
