# Generated by Django 4.1.2 on 2022-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_trainerprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinepost',
            name='post_caption1',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_caption2',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_caption3',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_title1',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_title2',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='headlinepost',
            name='post_title3',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
