# Generated by Django 4.1.2 on 2022-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
