# Generated by Django 4.1.2 on 2022-11-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_review_created_on'),
        ('clientlists', '0003_clientlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='clientprofile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile'),
        ),
    ]
