# Generated by Django 4.1.2 on 2022-11-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientlists', '0004_alter_clientlist_clientprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientList',
        ),
    ]
