# Generated by Django 4.1.2 on 2022-11-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientlists', '0006_clientlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlist',
            name='trainerprofile',
        ),
    ]
