# Generated by Django 4.1.2 on 2022-11-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlists', '0008_clientlist_trainerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlist',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
