# Generated by Django 4.1.2 on 2022-11-08 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_review_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientlists', '0009_clientlist_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time)),
                ('clientprofile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
