# Generated by Django 4.1.2 on 2022-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlists', '0011_session_trainerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
